<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <ul class="navbar-nav">
        <li class="nav-item text-white navcima ">
            Parque vivo
        </li>
        <li class="nav-item">
            <a href="pg_inicial.php"><span class="glyphicon glyphicon-home"></span></a>
        </li>
        <li class="nav-item">
            <a href="deslogar.php"><span class="glyphicon glyphicon-share"></span></a>
        </li>
  </ul>
</nav>