<nav class="navbar navbar-expand-sm bg-success navbar-dark fixed-top">
    <ul class="navbar-nav">
        <li class="nav-item text-white navcima ">
            Parque vivo
        </li>
        <li class="nav-item">
            <a href="perfil.php"><span class="glyphicon glyphicon-user"></span></a>
        </li>
        <li class="nav-item">
            <a href="pg_inicial.php"><span class="glyphicon glyphicon-home"></span></a>
        </li>
        <li class="nav-item">
            <a href="enviar_mensagem_usu.php"><span class="glyphicon glyphicon-comment"></span></a>
        </li>
        <li class="nav-item">
            <a href="cadastro_evento.php"><span class="glyphicon glyphicon-calendar"></span></a>
        </li>
        <li class="nav-item">
            <a href="evento_cadastrados_usu.php"><span class="glyphicon glyphicon glyphicon glyphicon-list-alt"></span></a>
        </li>
         <li class="nav-item">
            <a href="deslogar.php"><span class="glyphicon glyphicon-share"></span></a>
        </li>
  </ul>
</nav>